### ISSUE TITLE
redefinition of special functions like "draw" should probably be a warning

### ISSUE THREAD

**Issue by k4b7** [Khan/live-editor#193]
I've seen at least one student program where the student was redefining `draw`.  They had an if/else statement and put different versions of `draw` in each branch... something like this:

```
if (level === "level1") {
   draw = function () {
       ...
   };
} else if (level === "level2") {
   draw = function () {
       ...
   }
} else if ...
```

While a person can write a program like this and make it work, it's feels like bad practice.  I think the `if` statements where inside `mousePressed` or something like that.  Anyways, students should be following the structure provided in the "Animated scenes" lessons where draw is defined once and it multiplexes between several other functions, e.g.

```
draw = function() {
    if (currentScene === 4) {
        drawScene4();
    }
};
```

**Comment by JavascriptFTW** [comment]
It *is* bad practice to do it like that, but there are quite a few programs that do something *like* that, but not very bad at all style wise, i.e.
```
draw = function() {
    // do stuff
};
```
These programs would be broken if errors were thrown for redefining special functions. A better idea would be to throw a warning instead (which would require differentiation between errors and warnings which the error buddy currently can't do as far as I know).

**Comment by kevinb7** [comment]
Point taken.  We add gutter warnings when `Program.assertEqual` fails.  Updating BabyHint to differentiate errors from warnings sounds like a good idea.  I'm sure there's other stuff that we could warn against, e.g. setting event handlers inside the `draw` function is another thing I've seen people that's probably not a good idea.

@JavascriptFTW if you're planning to do something with BabyHint, you should know that I've started, but unfortunately have not finished, the process of extracting BabyHint into its own repo.  https://github.com/khan/BabyHint

**Comment by jjwon** [comment]
Isn't this more just a general issue of DRY, rather than anything particular to the `draw` function or any other special functions?

**Comment by kevinb7** [comment]
It's more best practices than anything else.  If a person were to redefine a mouse event handler inside a requestAnimationFrame callback, that's probably bad for performance and may cause weird issues especially if the previous mouse event handler isn't removed.
